services:
  - type: web
    name: HPC_notification
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb & rails db:migrate"
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
